[build]
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/config.yml"
  to = "/.netlify/functions/config"
  status = 200

# Ignore specific files from secrets scanning
[secrets_scanning]
  omit_paths = ["netlify/functions/auth-config.js"]
