[build]
  command = "npm run build"
  publish = "out"
  environment = { NODE_VERSION = "20.10.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  directory = "netlify/functions"

# Ignore specific files from secrets scanning
[secrets_scanning]
  omit_paths = ["netlify/functions/auth-config.js"]
