[build]
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[secrets_scanning]
  enabled = false
  omit_paths = ["admin/config.yml"]
