backend:
  name: git-gateway
  branch: main  # Change this to "master" if your default branch is named master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "goals"
    label: "Goals"
    folder: "content/goals"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["In Progress", "Future", "Achieved"] }
      - { label: "Progress (%)", name: "progress", widget: "number", value_type: "int", min: 0, max: 100 }
      - { label: "Image", name: "image", widget: "image", required: false }
