backend:
  name: auth0
  domain: petrolheadsgame.eu.auth0.com  # Your Auth0 domain
  client_id: wtqqTxmzjj1CyFm6CpbH1hAtAIfmcwm8  # Found in Auth0 dashboard
  scope: "openid profile email"
  redirect_uri: "https://petrolheadsgame.com/admin/"
  auth_type: "implicit"

local_backend: false

media_library:
  name: uploadcare
  config:
    publicKey: YOUR_UPLOADCARE_PUBLIC_KEY  # Optional

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
