backend:
  name: auth0
  auth_type: implicit
  app_id: YOUR_AUTH0_CLIENT_ID
  region: YOUR_AUTH0_REGION
  domain: YOUR_AUTH0_TENANT.auth0.com
  redirect_uri: https://petrolheadsgame.com/admin/
  api_url: https://petrolheadsgame.com/.netlify/functions/verify-auth0-token

auth_provider: netlify  # Allows Netlify Identity fallback if needed

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "goals"
    label: "Goals"
    folder: "content/goals"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["In Progress", "Future", "Achieved"] }
      - { label: "Progress (%)", name: "progress", widget: "number", value_type: "int", min: 0, max: 100 }
      - { label: "Image", name: "image", widget: "image", required: false }
