backend:
  name: auth0
  login: true
  domain: "YOUR_AUTH0_DOMAIN"
  client_id: "YOUR_AUTH0_CLIENT_ID"
  redirect_uri: "https://your-site.netlify.app/admin/"
  logout_url: "https://your-site.netlify.app/"
  scope: "openid profile email"
  audience: "https://YOUR_AUTH0_DOMAIN/api/v2/"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "goals"
    label: "Goals"
    folder: "content/goals"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["In Progress", "Future", "Achieved"] }
      - { label: "Progress (%)", name: "progress", widget: "number", value_type: "int", min: 0, max: 100 }
      - { label: "Image", name: "image", widget: "image", required: false }
