backend:
  name: proxy-backend
  proxy_url: "https://your-netlify-site.netlify.app/.netlify/functions/auth" # Netlify function to authenticate with Auth0
  branch: main  # Change to "master" if your repo uses master as the default branch

media_folder: "images/uploads"  # Where media files are stored
public_folder: "/images/uploads"

collections:
  - name: "goals"
    label: "Goals"
    folder: "content/goals"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["In Progress", "Future", "Achieved"] }
      - { label: "Progress (%)", name: "progress", widget: "number", value_type: "int", min: 0, max: 100 }
      - { label: "Image", name: "image", widget: "image", required: false }
