backend:
  name: auth0
  client_id: "${AUTH0_CLIENT_ID}" # Should match your actual Auth0 Client ID
  domain: "${AUTH0_DOMAIN}" # Should match your Auth0 domain (e.g., auth.petrolheadsgame.com)
  scope: "openid profile email"
  redirect_uri: "https://petrolheadsgame.com/admin/"
  auth_type: "implicit"

local_backend: false

media_library:
  name: uploadcare
  config:
    publicKey: YOUR_UPLOADCARE_PUBLIC_KEY  # Optional

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
