
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "key_features"
    label: "Key Features"
    folder: "content/key_features"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
  - name: "goals"
    label: "Goals"
    folder: "content/goals"
    create: true
    fields:
      - { name: "title", label: "Goal Title", widget: "string" }
      - { name: "status", label: "Status", widget: "select", options: ["Planned", "In Progress", "Completed"] }
      - { name: "description", label: "Goal Description", widget: "text" }
  - name: "media"
    label: "Media"
    folder: "content/media"
    create: true
    fields:
      - { name: "media_title", label: "Title", widget: "string" }
      - { name: "media_description", label: "Description", widget: "text" }
      - { name: "media_url", label: "Upload Media", widget: "image" }
      - { name: "media_type", label: "Type", widget: "select", options: ["Image", "Video"] }
