
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "media"
    label: "Media Gallery"
    folder: "content/media"
    create: true
    fields:
      - { name: "media_title", label: "Title", widget: "string" }
      - { name: "media_description", label: "Description", widget: "text" }
      - { name: "media_url", label: "Upload Media", widget: "image" }
      - { name: "media_type", label: "Type", widget: "select", options: ["Image", "Video"] }
